#include "motor_states.h"
#include "pins.h"

void motor_stop()
{
	CLR_MOTOR_GATE_1();
	CLR_MOTOR_GATE_2();
	CLR_MOTOR_GATE_3();
	CLR_MOTOR_GATE_4();
	CLR_MOTOR_GATE_5();
	CLR_MOTOR_GATE_6();
}

void test_gates_on()
{
	SET_MOTOR_GATE_1();
	SET_MOTOR_GATE_2();
	SET_MOTOR_GATE_3();
	SET_MOTOR_GATE_4();
	SET_MOTOR_GATE_5();
	SET_MOTOR_GATE_6();
}

void f1()
{
	SET_MOTOR_GATE_1();
	CLR_MOTOR_GATE_2();
	CLR_MOTOR_GATE_3();
	CLR_MOTOR_GATE_4();
	SET_MOTOR_GATE_5();
	CLR_MOTOR_GATE_6();
}

void f2()
{
	CLR_MOTOR_GATE_1();
	SET_MOTOR_GATE_2();
	CLR_MOTOR_GATE_3();
	CLR_MOTOR_GATE_4();
	CLR_MOTOR_GATE_5();
	SET_MOTOR_GATE_6();
}

void f3()
{
	CLR_MOTOR_GATE_1();
	CLR_MOTOR_GATE_2();
	SET_MOTOR_GATE_3();
	SET_MOTOR_GATE_4();
	CLR_MOTOR_GATE_5();
	CLR_MOTOR_GATE_6();
}

void b1()
{
	CLR_MOTOR_GATE_1();
	SET_MOTOR_GATE_2();
	CLR_MOTOR_GATE_3();
	SET_MOTOR_GATE_4();
	CLR_MOTOR_GATE_5();
	CLR_MOTOR_GATE_6();
}

void b2()
{
	SET_MOTOR_GATE_1();
	CLR_MOTOR_GATE_2();
	CLR_MOTOR_GATE_3();
	CLR_MOTOR_GATE_4();
	CLR_MOTOR_GATE_5();
	SET_MOTOR_GATE_6();
}

void b3()
{
	CLR_MOTOR_GATE_1();
	CLR_MOTOR_GATE_2();
	SET_MOTOR_GATE_3();
	CLR_MOTOR_GATE_4();
	SET_MOTOR_GATE_5();
	CLR_MOTOR_GATE_6();
}